### ISSUE TITLE
Status is not correct when accessing the survey through the public link (public view)

### ISSUE THREAD

**Issue by marieanik** [bcgov/met-public#1305] opened 2023-03-01 19:25 UTC
If I click the link to access an open survey, the status badge shows as upcoming even if the survey is open.![Screenshot 2023-03-01 at 11.24.07 AM.png](https://images.zenhubusercontent.com/6261bc1a04c6a94c2edadddd/fd9529ba-6f36-4b30-9cc9-a30e8701ad36)

**Comment by VineetBala-AOT** [comment] 2023-03-07 17:48
Closing it as not able to reproduce the issue anymore. Could have been due to delay in the job which changes the status of the scheduled engagement to open. Currently the job is scheduled to run every 5th minute so even if a engagement is scheduled to open now it will open only at the 5th minute.

**Closed by VineetBala-AOT** 2023-03-07 17:48 UTC
Labels: bug
