### ISSUE TITLE
Team member cannot assign a role/engagement to a user from the UM Listing page (when user is without a role)

### ISSUE THREAD

**Issue by TayaLee8** [bcgov/met-public#1910] opened 2023-07-27 21:17 UTC
[Private Zenhub Image]

Superuser must assign a role to a user. (If the user has just been added in the system, a superuser must assign them a role before they are added to the system. They are also the only one that can reassign a role #1907)

A Team Member can only assign a user that is already a TM to an assignment. They shouldn't see the options to assign a role, or reassign a role in the action drop-down. They should only see the "Assign to an Engagement" option when the user is already a TM.

Logged in as Superuser (UM listing page) 
Action drop-down options:

- no role assigned yet: Assign Role
- Viewer: Reassign Role
- Reviewer: Add to Engagement, Reassign Role
- TM: Add to Engagement, Reassign Role
- Superuser: Reassign Role

Logged in as TM (UM listing page)
Action drop-down options:

- no role assigned yet: --
- Viewer: --
- Reviewer: --
- TM: Add to Engagement
- Superuser: --

Logged in as Superuser (UM listing page)

A Team Member should be able to assign users to an engagement that they are assigned to (https://app.zenhub.com/workspaces/met-ops-6254279dcfa60b0010ea5a0d/issues/gh/bcgov/met-public/2026 covers only viewing in the modal the engagement the TM can assign another TM to).

Reported by Taya as Team Member

(https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBczBIIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--f9bca13af15226fc96d9ed9b1ddb0b872408704d/Screenshot%202023-08-15%20at%2012.44.43%20PM.png)

**Comment by TayaLee8** [comment] 2023-08-23 22:23
As a Team Member:
Failing in DEV > As a TM, I can still assign a **Reviewer** to an engagement that I am assigned to. I should only be able to assign another TM. 

As a Superuser (This may be under development in another ticket but making note of it here):
Drop downs have not been updated > Superusers and Viewers have no drop down options. Reviewers and TM's only have 'Assign to Engagement' option.

**Comment by VineetBala-AOT** [comment] 2023-08-25 00:11
Closing this ticket:
- As per the discussion TM can assign a Reviewer to an engagement that TM is assigned to. This is intended behavior.
- Superusers and Viewers have no drop down options as of now but will have once we have the reassign ticket completed.

**Comment by VineetBala-AOT** [comment] 2023-08-25 00:11
Closing this ticket:
- As per the discussion TM can assign a Reviewer to an engagement that TM is assigned to. This is intended behavior.
- Superusers and Viewers have no drop down options as of now but will have once we have the reassign ticket completed.

**Closed by VineetBala-AOT** 2023-08-25 00:11 UTC
Labels: bug, UM testing
