### ISSUE TITLE
Engagement Listing Page Redesign

### ISSUE THREAD

**Issue by saravanpa-aot** [bcgov/met-public#1238] opened 2023-02-14 19:27 UTC
AS an Staff user 
I want the engagement page list view to show different actions
depending on the role of the user

UI Based ticket

**Comment by carlygreenehill** [comment] 2023-02-14 19:30
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/MET-Ops-6254279dcfa60b0010ea5a0d/issues/bcgov/met-public/1238?planning-poker) with Zenhub @djnunez-aot @jadmsaadaot @saravanpa-aot @VineetBala-AOT

**Comment by carlygreenehill** [comment] 2023-02-14 19:34
DESIGN THE TABLE

**Comment by carlygreenehill** [comment] 2023-04-24 21:27
duplicate of 1239

**Closed by carlygreenehill** 2023-04-24 21:27 UTC
Labels: emli
