### ISSUE TITLE
Engagement Form: Add a save button in settings tab and handle save separately

### ISSUE THREAD

**Issue by jadmsaadaot** [bcgov/met-public#1481] opened 2023-04-10 18:13 UTC
Right now we have to navigate back to Details tab to save meta data. We also have an issue with the notification, whenever you save the engagement even if you didn't change the meta data the message will be meta data is saved.

**Comment by tiagograf-AOT** [comment] 2023-04-10 18:48
duplicate of #1442

**Closed by tiagograf-AOT** 2023-04-10 18:48 UTC
Labels: bug, firm-up
