### ISSUE TITLE
Overlapping text - Engagements>advanced search

### ISSUE THREAD

**Issue by Ian-UX-AOT** [bcgov/met-public#1820] opened 2023-07-10 20:31 UTC
As a super user/team member it would be easier for me to understand the advanced search section if the status section wasn't overlapping project name & project # sections and if the button text was centred. This would give me an easier understanding of entering information when doing this task.
Viewed on nest hub tablet - 1024x600

![Screenshot 2023-07-10 at 1.20.57 PM.png](https://images.zenhubusercontent.com/63c595f1d8ede2145e2c4ad4/3cb65a03-e1f8-4771-943b-c1ac0f79891b)

**Comment by marieanik** [comment] 2023-08-14 22:08
Duplicate of #1520

**Closed** 2023-08-14 22:08 UTC
Labels: bug
